import Head from 'next/head'
import { useEffect } from 'react'
const Meta = ({title,content,dark}) => {
  useEffect(()=>{
    if(dark){
      document.querySelector("html").classList.add("dark")
    }else{
      document.querySelector("html").classList.remove("dark")
    }
  },[dark])
  return (
    <div>
        <Head>
            <meta charSet="UTF-8" />
            <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
            {/* <meta name="viewport" content="width=device-width, initial-scale=1.0" /> */}
            <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
            <meta name='keywords' content={content} />
            <meta name="description" content="Generated by create next app" />
            <title>{title}</title>
        </Head>
    </div>
  )
}

export default Meta